DROP TABLE IF EXISTS Events CASCADE;
DROP TABLE IF EXISTS Notes CASCADE;
DROP TABLE IF EXISTS Purchases CASCADE;
DROP TABLE IF EXISTS People CASCADE;
DROP TABLE IF EXISTS Files CASCADE;
DROP TABLE IF EXISTS Directories CASCADE;

CREATE TABLE Events (
    eventID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    title VARCHAR(100) NOT NULL,
    description TEXT,
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL, --n sabo
    location TEXT, --por enquanto
);

CREATE TABLE Notes (
    noteID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    title VARCHAR(100) NOT NULL,
    content TEXT NOT NULL,
);

CREATE TABLE Purchases (
    purchaseID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    product VARCHAR(100) NOT NULL,
    store TEXT NOT NULL,
    description TEXT,
    price INT NOT NULL,
    purchase_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);