DROP TABLE IF EXISTS People CASCADE;
DROP TABLE IF EXISTS Purchases CASCADE;


CREATE TABLE People (
    peopleID INT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    age INT,
    description TEXT,
);

CREATE TABLE Purchases (
    purchaseID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    product VARCHAR(100) NOT NULL,
    store TEXT NOT NULL,
    description TEXT,
    price INT NOT NULL,
    purchase_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);